[project]
name = "wise-move-api-format"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "uvicorn>=0.34.2",
]
